project:
  type: website
  title: "Gary Touet - Freelance Lead Data Analyst & Product Manager"
  preview:
    port: 4200
    browser: true

website:
  title: "Gary Touet"
  description: "Freelance Lead Data Analyst & Product Manager"
  site-url: "https://garytouet.com"
  navbar:
    collapse: false
    search: true
    right:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
  #announcement:
    #icon: info-circle
    #dismissable: false
    #content: "**Alert** - this is some information that you should pay attention to"
    #type: info
    #position: below-navbar
  bread-crumbs: true
  page-footer:
    border: true
    left: Powered by [Quarto](https://quarto.org)
    center: © 2025 Gary Touet
    right:
      - icon: mastodon
        href: https://mastodon.social/@garytouet
      - icon: linkedin
        href: https://www.linkedin.com/in/garytouet/
      - icon: github
        href: https://github.com/garytouet
      - icon: envelope-at
        href: mailto:hello@garytouet.com
      - icon: rss
        href: posts.xml
format:
  html:
    template-partials:
      - /partials/title-block.html
    theme: 
      - zephyr
      - custom.scss
    toc: true
    toc-location: right
    #code-fold: true
    code-tools: false
    smooth-scroll: true
    code-overflow: wrap
    title-block-banner: false
    number-sections: false
    highlight-style: arrow
    link-external-icon: true
    link-external-newwindow: false
    date-format: "iso"
    include-in-header:
      - text: |
          <link rel="icon" href="favicon.ico" sizes="32x32">
          <link rel="icon" href="/icons/favicon_96x96.png" sizes="96x96">
          <link rel="icon" href="/icons/icon.svg" type="image/svg+xml">
          <link rel="apple-touch-icon" href="apple-touch-icon.png">

execute:
  freeze: auto